spring.autoconfigure.exclude: org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration, org.springframework.cloud.aws.autoconfigure.context.ContextCredentialsAutoConfiguration, org.springframework.cloud.aws.autoconfigure.context.ContextResourceLoaderAutoConfiguration, org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
cloud.aws.region.static: eu-west-1

